# Generated by Django 5.1.15 on 2026-02-14 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="JunkbinItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[("have", "Have"), ("want", "Want")],
                        help_text="Whether user has or wants this item",
                        max_length=4,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available for Trade"),
                            ("not_for_trade", "Not for Trade"),
                        ],
                        default="not_for_trade",
                        help_text='Trade availability (only for "have" items)',
                        max_length=15,
                    ),
                ),
                (
                    "condition",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("working", "Working"),
                            ("broken", "Broken / For Parts"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        help_text='Item condition (only for "have" items)',
                        max_length=10,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[("public", "Public"), ("private", "Private")],
                        default="public",
                        help_text="Whether this item is publicly visible",
                        max_length=7,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Optional notes about this item",
                        max_length=500,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(default=1, help_text="Number of units"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"model__in": ("product", "component")},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="junkbin_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "junkbin item",
                "verbose_name_plural": "junkbin items",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "item_type"],
                        name="junkbin_jun_user_id_9ef5f8_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="junkbin_jun_content_9779a0_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "content_type", "object_id", "item_type"),
                        name="unique_junkbin_item",
                    )
                ],
            },
        ),
    ]
