# Generated by Django 5.1.15 on 2026-02-14 21:12

import apps.recipes.models
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0005_productcomponent_confirm_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(help_text="Recipe name", max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                (
                    "description",
                    models.TextField(
                        help_text="Describe what this recipe builds and how"
                    ),
                ),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("expert", "Expert"),
                        ],
                        help_text="Difficulty level",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("audio", "Audio"),
                            ("power_supply", "Power Supply"),
                            ("iot", "IoT"),
                            ("repair", "Repair"),
                            ("lighting", "Lighting"),
                            ("test_equipment", "Test Equipment"),
                            ("radio", "Radio"),
                            ("computing", "Computing"),
                            ("robotics", "Robotics"),
                            ("wearable", "Wearable"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Project category",
                        max_length=20,
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True, help_text="Link to project tutorial or instructions"
                    ),
                ),
                (
                    "estimated_time",
                    models.CharField(
                        blank=True,
                        help_text='Estimated build time, e.g. "2-3 hours"',
                        max_length=100,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Hero image for the recipe",
                        null=True,
                        upload_to=apps.recipes.models.recipe_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, help_text="Whether recipe has been approved"
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured on the recipes page"
                    ),
                ),
                (
                    "component_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Number of required (non-optional) BOM items",
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times viewed"
                    ),
                ),
                (
                    "build_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of builds (future use)"
                    ),
                ),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(
                        editable=False, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_recipes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe",
                "verbose_name_plural": "recipes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RecipeComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of this component needed"
                    ),
                ),
                (
                    "notes",
                    models.CharField(
                        blank=True,
                        help_text='Notes, e.g. "any value 100-470uF works"',
                        max_length=500,
                    ),
                ),
                (
                    "is_optional",
                    models.BooleanField(
                        default=False,
                        help_text="Optional components excluded from match denominator",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="components.component",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_components",
                        to="recipes.recipe",
                    ),
                ),
            ],
            options={
                "verbose_name": "recipe component",
                "verbose_name_plural": "recipe components",
                "ordering": ["component__manufacturer", "component__part_number"],
            },
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["category", "-created_at"],
                name="recipes_rec_categor_54b6b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["difficulty", "-created_at"],
                name="recipes_rec_difficu_1664ce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["is_approved", "-created_at"],
                name="recipes_rec_is_appr_a0d0dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="recipes_rec_search__ce256b_gin"
            ),
        ),
        migrations.AddConstraint(
            model_name="recipecomponent",
            constraint=models.UniqueConstraint(
                fields=("recipe", "component"), name="unique_recipe_component"
            ),
        ),
    ]
