# Generated by Django 5.1.15 on 2026-02-02 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_trusted", "Granted Trusted Status"),
                            ("user_untrusted", "Revoked Trusted Status"),
                            ("user_moderator", "Granted Moderator Status"),
                            ("user_unmoderator", "Revoked Moderator Status"),
                            ("user_suspended", "Suspended User"),
                            ("user_unsuspended", "Unsuspended User"),
                            ("product_approved", "Approved Product"),
                            ("product_unapproved", "Unapproved Product"),
                            ("product_featured", "Featured Product"),
                            ("submission_approved", "Approved Submission"),
                            ("submission_rejected", "Rejected Submission"),
                            ("component_verified", "Verified Component"),
                            ("report_resolved", "Resolved Report"),
                            ("other", "Other Action"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "target_model",
                    models.CharField(
                        help_text="Model type affected (e.g., User, Product)",
                        max_length=100,
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        help_text="ID of the affected object", max_length=100
                    ),
                ),
                (
                    "target_repr",
                    models.CharField(
                        blank=True,
                        help_text="String representation of the target at action time",
                        max_length=255,
                    ),
                ),
                (
                    "details",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional action details and changes made",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        help_text="Admin who performed the action",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "admin audit log",
                "verbose_name_plural": "admin audit logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin_user", "-created_at"],
                        name="users_admin_admin_u_d02db6_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="users_admin_action__9808fb_idx",
                    ),
                    models.Index(
                        fields=["target_model", "target_id"],
                        name="users_admin_target__222c48_idx",
                    ),
                ],
            },
        ),
    ]
