# Generated by Django 5.1.15 on 2026-02-13 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_adminauditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="messaging_blocked",
            field=models.BooleanField(
                default=False,
                help_text="User is blocked from sending/receiving messages (set by moderators)",
            ),
        ),
        migrations.AlterField(
            model_name="adminauditlog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("user_trusted", "Granted Trusted Status"),
                    ("user_untrusted", "Revoked Trusted Status"),
                    ("user_moderator", "Granted Moderator Status"),
                    ("user_unmoderator", "Revoked Moderator Status"),
                    ("user_suspended", "Suspended User"),
                    ("user_unsuspended", "Unsuspended User"),
                    ("messaging_blocked", "Blocked User Messaging"),
                    ("messaging_unblocked", "Unblocked User Messaging"),
                    ("product_approved", "Approved Product"),
                    ("product_unapproved", "Unapproved Product"),
                    ("product_featured", "Featured Product"),
                    ("submission_approved", "Approved Submission"),
                    ("submission_rejected", "Rejected Submission"),
                    ("component_verified", "Verified Component"),
                    ("report_resolved", "Resolved Report"),
                    ("other", "Other Action"),
                ],
                max_length=30,
            ),
        ),
    ]
