# Generated by Django 5.1.15 on 2026-02-15 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_messaging_blocked_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="badges",
            field=models.JSONField(
                blank=True, default=list, help_text="Earned badges and achievements"
            ),
        ),
    ]
