# Generated by Django 5.1.15 on 2026-03-02 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_badges"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="preferred_language",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Preferred UI language code (e.g. en, de, pl)",
                max_length=10,
            ),
        ),
    ]
