# Generated by Django 5.1.15 on 2026-08-28 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0006_alter_adminauditlog_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="forward_messages_to",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, a copy of every message this user receives is also sent to this delegate, who can reply on their behalf.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="forwarded_from_users",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("forward_messages_to", models.F("id")), _negated=True
                ),
                name="no_self_message_forward",
            ),
        ),
    ]
