# Generated by Django 5.2.17 on 2026-08-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0007_user_forward_messages_to_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-reputation_score"], name="users_user_reputat_7fc0a1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["-contribution_count"], name="users_user_contrib_a9eb73_idx"
            ),
        ),
    ]
