# Generated by Django 5.1.15 on 2026-08-28 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_message_content_messageattachment"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="forwarded_from_conversation",
            field=models.ForeignKey(
                blank=True,
                help_text="Set only on auto-forwarded copies/relays: the conversation this message was mirrored from or back into (see forward_messages_to).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="messaging.conversation",
            ),
        ),
    ]
