# Generated by Django 5.1.15 on 2026-01-29 13:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Component",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        db_index=True,
                        help_text="Manufacturer part number",
                        max_length=200,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        db_index=True,
                        help_text="Component manufacturer",
                        max_length=200,
                    ),
                ),
                (
                    "manufacturer_aliases",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternative manufacturer names",
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("ic", "Integrated Circuit"),
                            ("mcu", "Microcontroller"),
                            ("transistor", "Transistor"),
                            ("mosfet", "MOSFET"),
                            ("diode", "Diode"),
                            ("regulator", "Voltage Regulator"),
                            ("opamp", "Op-Amp"),
                            ("resistor", "Resistor"),
                            ("capacitor", "Capacitor"),
                            ("inductor", "Inductor"),
                            ("transformer", "Transformer"),
                            ("crystal", "Crystal/Oscillator"),
                            ("fuse", "Fuse"),
                            ("ferrite", "Ferrite Bead"),
                            ("relay", "Relay"),
                            ("switch", "Switch"),
                            ("connector", "Connector"),
                            ("socket", "Socket/Header"),
                            ("antenna", "Antenna"),
                            ("rf_module", "RF Module"),
                            ("balun", "Balun/Filter"),
                            ("battery", "Battery/Cell"),
                            ("power_jack", "Power Jack/Barrel"),
                            ("usb_port", "USB Port"),
                            ("led", "LED"),
                            ("display", "Display/LCD"),
                            ("speaker", "Speaker/Buzzer"),
                            ("sensor", "Sensor"),
                            ("thermistor", "Thermistor/NTC"),
                            ("module", "Module/Daughter Board"),
                            ("pcb_assembly", "PCB Assembly"),
                            ("cable", "Cable/Wire Harness"),
                            ("flex_cable", "Flex Cable/FPC"),
                            ("coax", "Coaxial Cable"),
                            ("heatsink", "Heatsink"),
                            ("shield", "EMI Shield"),
                            ("mechanical", "Mechanical Part"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Type of component",
                        max_length=50,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        help_text="Package type (SOT-23, SOIC-8, 0805, etc.)",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Component description"),
                ),
                (
                    "typical_function",
                    models.CharField(
                        blank=True,
                        help_text="Typical application (voltage regulator, MCU, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "specifications",
                    models.JSONField(
                        blank=True, default=dict, help_text="Technical specifications"
                    ),
                ),
                (
                    "datasheet_url",
                    models.URLField(blank=True, help_text="Link to datasheet"),
                ),
                (
                    "octopart_url",
                    models.URLField(blank=True, help_text="Octopart listing URL"),
                ),
                (
                    "alternative_part_numbers",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Alternative part numbers for this component",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Component information has been verified",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of products containing this component",
                    ),
                ),
            ],
            options={
                "verbose_name": "component",
                "verbose_name_plural": "components",
                "ordering": ["manufacturer", "part_number"],
            },
        ),
        migrations.CreateModel(
            name="ProductComponent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reference_designator",
                    models.CharField(
                        blank=True,
                        help_text="Reference designator (U1, R5, C12, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1, help_text="Number of this component on the board"
                    ),
                ),
                (
                    "location_description",
                    models.CharField(
                        blank=True,
                        help_text="Description of location (near HDMI port, on power board, etc.)",
                        max_length=200,
                    ),
                ),
                (
                    "board_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of the PCB if product has multiple boards",
                        max_length=100,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes about this component in this product",
                    ),
                ),
                (
                    "submission_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic (Major Components)"),
                            ("advanced", "Advanced (Complete BOM)"),
                        ],
                        default="basic",
                        help_text="Level of detail for this entry",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="This component mapping has been verified",
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "product component",
                "verbose_name_plural": "product components",
                "ordering": ["reference_designator", "component__part_number"],
            },
        ),
    ]
