# Generated by Django 5.1.15 on 2026-01-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("components", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="component",
            name="cross_references",
            field=models.ManyToManyField(
                blank=True, help_text="Equivalent parts", to="components.component"
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="component",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_components",
                to="components.component",
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_product_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="image_reference",
            field=models.ForeignKey(
                blank=True,
                help_text="Image showing this component",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="products.productimage",
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_components",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="verified_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="verified_product_components",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["part_number"], name="components__part_nu_3dc2f1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["manufacturer", "part_number"],
                name="components__manufac_b7f6a7_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=models.Index(
                fields=["component_type", "-usage_count"],
                name="components__compone_f0dbfe_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="component",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "part_number"), name="unique_component"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["product", "component"], name="components__product_981792_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productcomponent",
            index=models.Index(
                fields=["component", "is_verified"],
                name="components__compone_1dad04_idx",
            ),
        ),
    ]
