# Generated by Django 5.1.15 on 2026-02-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productcomponent",
            name="reference_designator",
            field=models.CharField(
                blank=True,
                help_text='Reference designator(s), e.g. "U1" or "C1, C3, C8, C10"',
                max_length=255,
            ),
        ),
    ]
