# Generated by Django 5.1.15 on 2026-02-13 02:37

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0003_increase_reference_designator_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="component",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddIndex(
            model_name="component",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="components__search__ed88f3_gin"
            ),
        ),
    ]
