# Generated by Django 5.1.15 on 2026-02-13 21:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0004_search_optimization"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomponent",
            name="confirm_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of confirm votes"
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="dispute_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of dispute votes"
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="needs_review",
            field=models.BooleanField(
                default=False, help_text="Flagged for moderator review due to disputes"
            ),
        ),
        migrations.AddField(
            model_name="productcomponent",
            name="vote_score",
            field=models.IntegerField(
                default=0, help_text="Net weighted score (confirms - disputes)"
            ),
        ),
        migrations.CreateModel(
            name="ComponentVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote_type",
                    models.CharField(
                        choices=[("confirm", "Confirm"), ("dispute", "Dispute")],
                        max_length=10,
                    ),
                ),
                (
                    "weight",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Vote weight, set at vote time based on trust status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="components.productcomponent",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "component vote",
                "verbose_name_plural": "component votes",
                "indexes": [
                    models.Index(
                        fields=["product_component", "vote_type"],
                        name="components__product_106ca5_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="components__user_id_77c1a8_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product_component", "user"),
                        name="unique_vote_per_user",
                    )
                ],
            },
        ),
    ]
