# Generated by Django 5.1.15 on 2026-02-15 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0005_productcomponent_confirm_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentViewStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True)),
                ("view_count", models.IntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="view_stats",
                        to="components.component",
                    ),
                ),
            ],
            options={
                "verbose_name": "component view stats",
                "verbose_name_plural": "component view stats",
                "unique_together": {("component", "date")},
            },
        ),
    ]
