# Generated by Django 5.1.15 on 2026-02-17 19:15

import apps.components.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0006_componentviewstats"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Component image",
                        upload_to=apps.components.models.component_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
                            )
                        ],
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("package", "Package Photo"),
                            ("markings", "Markings/Labels"),
                            ("closeup", "Close-up Detail"),
                            ("pinout", "Pinout Reference"),
                            ("application", "Application/In-Circuit"),
                            ("other", "Other"),
                        ],
                        default="package",
                        max_length=20,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Image caption or description",
                        max_length=500,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order in image gallery"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether image has been approved by moderator",
                    ),
                ),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="components.component",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_component_images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "component image",
                "verbose_name_plural": "component images",
                "ordering": ["display_order", "uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["is_approved", "-uploaded_at"],
                        name="components__is_appr_3adfa1_idx",
                    )
                ],
            },
        ),
    ]
