# Generated by Django 5.1.15 on 2026-02-17 19:47

import apps.components.models
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0007_add_component_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentTypeImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "component_type",
                    models.CharField(
                        choices=[
                            ("ic", "Integrated Circuit"),
                            ("mcu", "Microcontroller"),
                            ("transistor", "Transistor"),
                            ("mosfet", "MOSFET"),
                            ("diode", "Diode"),
                            ("regulator", "Voltage Regulator"),
                            ("opamp", "Op-Amp"),
                            ("resistor", "Resistor"),
                            ("capacitor", "Capacitor"),
                            ("inductor", "Inductor"),
                            ("transformer", "Transformer"),
                            ("crystal", "Crystal/Oscillator"),
                            ("fuse", "Fuse"),
                            ("ferrite", "Ferrite Bead"),
                            ("relay", "Relay"),
                            ("switch", "Switch"),
                            ("connector", "Connector"),
                            ("socket", "Socket/Header"),
                            ("antenna", "Antenna"),
                            ("rf_module", "RF Module"),
                            ("balun", "Balun/Filter"),
                            ("battery", "Battery/Cell"),
                            ("power_jack", "Power Jack/Barrel"),
                            ("usb_port", "USB Port"),
                            ("led", "LED"),
                            ("display", "Display/LCD"),
                            ("speaker", "Speaker/Buzzer"),
                            ("sensor", "Sensor"),
                            ("thermistor", "Thermistor/NTC"),
                            ("module", "Module/Daughter Board"),
                            ("pcb_assembly", "PCB Assembly"),
                            ("cable", "Cable/Wire Harness"),
                            ("flex_cable", "Flex Cable/FPC"),
                            ("coax", "Coaxial Cable"),
                            ("heatsink", "Heatsink"),
                            ("shield", "EMI Shield"),
                            ("mechanical", "Mechanical Part"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Component type this image represents",
                        max_length=50,
                    ),
                ),
                (
                    "package_type",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Package type (e.g., 0603, SOT-23). Leave blank for a type-wide default.",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Default image for this type/package combination",
                        upload_to=apps.components.models.type_image_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
                            )
                        ],
                    ),
                ),
            ],
            options={
                "verbose_name": "component type image",
                "verbose_name_plural": "component type images",
                "ordering": ["component_type", "package_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("component_type", "package_type"),
                        name="unique_type_package_image",
                    )
                ],
            },
        ),
    ]
