# Generated by Django 5.1.15 on 2026-03-01 00:29

import apps.components.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0008_add_component_type_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentDatasheet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.components.models.datasheet_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "png", "jpg", "jpeg", "svg"]
                            )
                        ],
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("version", models.CharField(blank=True, max_length=50)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official", "Official Manufacturer"),
                            ("community", "Community Upload"),
                            ("reverse_eng", "Reverse Engineered"),
                            ("mirror", "Third-party Mirror"),
                        ],
                        default="official",
                        max_length=30,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_notes", models.TextField(blank=True)),
                ("file_type", models.CharField(blank=True, max_length=10)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "component",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasheets",
                        to="components.component",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="component_datasheets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
