# Generated by Django 5.1.15 on 2026-08-08 22:52

import apps.components.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0009_componentdatasheet"),
    ]

    operations = [
        migrations.AlterField(
            model_name="component",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("ic", "Integrated Circuit"),
                    ("mcu", "Microcontroller"),
                    ("eeprom", "EEPROM/Memory"),
                    ("transistor", "Transistor"),
                    ("mosfet", "MOSFET"),
                    ("diode", "Diode"),
                    ("regulator", "Voltage Regulator"),
                    ("opamp", "Op-Amp"),
                    ("resistor", "Resistor"),
                    ("capacitor", "Capacitor"),
                    ("inductor", "Inductor"),
                    ("transformer", "Transformer"),
                    ("crystal", "Crystal/Oscillator"),
                    ("fuse", "Fuse"),
                    ("ferrite", "Ferrite Bead"),
                    ("relay", "Relay"),
                    ("switch", "Switch"),
                    ("connector", "Connector"),
                    ("socket", "Socket/Header"),
                    ("antenna", "Antenna"),
                    ("rf_module", "RF Module"),
                    ("balun", "Balun/Filter"),
                    ("battery", "Battery/Cell"),
                    ("power_jack", "Power Jack/Barrel"),
                    ("usb_port", "USB Port"),
                    ("led", "LED"),
                    ("display", "Display/LCD"),
                    ("speaker", "Speaker/Buzzer"),
                    ("sensor", "Sensor"),
                    ("thermistor", "Thermistor/NTC"),
                    ("module", "Module/Daughter Board"),
                    ("pcb_assembly", "PCB Assembly"),
                    ("cable", "Cable/Wire Harness"),
                    ("flex_cable", "Flex Cable/FPC"),
                    ("coax", "Coaxial Cable"),
                    ("heatsink", "Heatsink"),
                    ("shield", "EMI Shield"),
                    ("mechanical", "Mechanical Part"),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="Type of component",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="componentdatasheet",
            name="file",
            field=models.FileField(
                upload_to=apps.components.models.datasheet_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf", "png", "jpg", "jpeg", "jfif", "svg"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="componentimage",
            name="image",
            field=models.ImageField(
                help_text="Component image",
                upload_to=apps.components.models.component_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "png",
                            "jpg",
                            "jpeg",
                            "jfif",
                            "gif",
                            "webp",
                            "avif",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="componenttypeimage",
            name="component_type",
            field=models.CharField(
                choices=[
                    ("ic", "Integrated Circuit"),
                    ("mcu", "Microcontroller"),
                    ("eeprom", "EEPROM/Memory"),
                    ("transistor", "Transistor"),
                    ("mosfet", "MOSFET"),
                    ("diode", "Diode"),
                    ("regulator", "Voltage Regulator"),
                    ("opamp", "Op-Amp"),
                    ("resistor", "Resistor"),
                    ("capacitor", "Capacitor"),
                    ("inductor", "Inductor"),
                    ("transformer", "Transformer"),
                    ("crystal", "Crystal/Oscillator"),
                    ("fuse", "Fuse"),
                    ("ferrite", "Ferrite Bead"),
                    ("relay", "Relay"),
                    ("switch", "Switch"),
                    ("connector", "Connector"),
                    ("socket", "Socket/Header"),
                    ("antenna", "Antenna"),
                    ("rf_module", "RF Module"),
                    ("balun", "Balun/Filter"),
                    ("battery", "Battery/Cell"),
                    ("power_jack", "Power Jack/Barrel"),
                    ("usb_port", "USB Port"),
                    ("led", "LED"),
                    ("display", "Display/LCD"),
                    ("speaker", "Speaker/Buzzer"),
                    ("sensor", "Sensor"),
                    ("thermistor", "Thermistor/NTC"),
                    ("module", "Module/Daughter Board"),
                    ("pcb_assembly", "PCB Assembly"),
                    ("cable", "Cable/Wire Harness"),
                    ("flex_cable", "Flex Cable/FPC"),
                    ("coax", "Coaxial Cable"),
                    ("heatsink", "Heatsink"),
                    ("shield", "EMI Shield"),
                    ("mechanical", "Mechanical Part"),
                    ("other", "Other"),
                ],
                db_index=True,
                help_text="Component type this image represents",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="componenttypeimage",
            name="image",
            field=models.ImageField(
                help_text="Default image for this type/package combination",
                upload_to=apps.components.models.type_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "png",
                            "jpg",
                            "jpeg",
                            "jfif",
                            "gif",
                            "webp",
                            "avif",
                        ]
                    )
                ],
            ),
        ),
    ]
