# Generated by Django 5.1.15 on 2026-08-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0010_alter_component_component_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="componentimage",
            name="background_removed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this image has had its background auto-removed",
            ),
        ),
        migrations.AddField(
            model_name="componentimage",
            name="has_transparency",
            field=models.BooleanField(
                default=False,
                help_text="Whether this image already has a transparent background",
            ),
        ),
    ]
