# Generated by Django 5.1.15 on 2026-02-15 15:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebhookEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Friendly name, e.g. "#new-products channel"',
                        max_length=200,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("discord", "Discord"), ("slack", "Slack")],
                        max_length=10,
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        help_text="The webhook URL (token is embedded in the URL)"
                    ),
                ),
                (
                    "events",
                    models.JSONField(
                        default=list,
                        help_text="List of event type strings to subscribe to",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "webhook endpoint",
                "verbose_name_plural": "webhook endpoints",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WebhookDelivery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("payload", models.JSONField()),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_body", models.TextField(blank=True)),
                ("success", models.BooleanField(default=False)),
                ("attempted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliveries",
                        to="webhooks.webhookendpoint",
                    ),
                ),
            ],
            options={
                "verbose_name": "webhook delivery",
                "verbose_name_plural": "webhook deliveries",
                "ordering": ["-attempted_at"],
                "indexes": [
                    models.Index(
                        fields=["endpoint", "-attempted_at"],
                        name="webhooks_we_endpoin_1c5984_idx",
                    )
                ],
            },
        ),
    ]
