# Generated by Django 5.1.15 on 2026-01-29 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubmissionComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "submission comment",
                "verbose_name_plural": "submission comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Submission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "submission_type",
                    models.CharField(
                        choices=[
                            ("new_product", "New Product"),
                            ("update_existing", "Update Existing"),
                            ("component_addition", "Component Addition"),
                            ("image_addition", "Image Addition"),
                            ("bulk_import", "Bulk Import"),
                        ],
                        help_text="Type of submission",
                        max_length=30,
                    ),
                ),
                (
                    "submission_level",
                    models.CharField(
                        choices=[
                            ("basic", "Basic (Major Components Only)"),
                            ("advanced", "Advanced (Complete BOM)"),
                        ],
                        default="basic",
                        help_text="Level of detail",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending Review"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("needs_changes", "Needs Changes"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "changes_summary",
                    models.TextField(blank=True, help_text="Summary of changes made"),
                ),
                (
                    "changes_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Detailed change data for audit",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "review_notes",
                    models.TextField(blank=True, help_text="Notes from reviewer"),
                ),
                (
                    "auto_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this was auto-approved (trusted user)",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submissions",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "submission",
                "verbose_name_plural": "submissions",
                "ordering": ["-submitted_at"],
            },
        ),
    ]
