# Generated by Django 5.1.15 on 2026-01-29 13:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic (3 Strike Threshold)"),
                            ("manual", "Manual Review Request"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "trigger_report_count",
                    models.PositiveIntegerField(
                        default=0, help_text="User report count at time of trigger"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("in_progress", "In Progress"),
                            ("cleared", "Cleared"),
                            ("warning_issued", "Warning Issued"),
                            ("restricted", "Account Restricted"),
                            ("suspended", "Account Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Internal notes about the review"
                    ),
                ),
                (
                    "action_taken",
                    models.TextField(
                        blank=True, help_text="Description of action taken"
                    ),
                ),
            ],
            options={
                "verbose_name": "user review",
                "verbose_name_plural": "user reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("object_id", models.UUIDField(help_text="ID of the reported item")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("incorrect_info", "Incorrect Information"),
                            ("duplicate", "Duplicate Entry"),
                            ("spam", "Spam/Advertising"),
                            ("inappropriate", "Inappropriate Content"),
                            ("copyright", "Copyright Violation"),
                            ("other", "Other"),
                        ],
                        help_text="Reason for report",
                        max_length=20,
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Detailed description of the issue"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("investigating", "Under Investigation"),
                            ("resolved_valid", "Resolved - Valid"),
                            ("resolved_invalid", "Resolved - Invalid"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("resolution_notes", models.TextField(blank=True)),
                (
                    "counted_as_strike",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this report counted against the user",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        help_text="Type of content being reported",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "report",
                "verbose_name_plural": "reports",
                "ordering": ["-created_at"],
            },
        ),
    ]
