# Generated by Django 5.1.15 on 2026-01-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reported_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reports_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="report",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="resolved_reports",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="related_reports",
            field=models.ManyToManyField(
                blank=True, related_name="user_reviews", to="reports.report"
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="conducted_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="triggered_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Report that triggered this review",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reports.report",
            ),
        ),
        migrations.AddField(
            model_name="userreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "-created_at"], name="reports_rep_status_7dd5e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["reported_user", "counted_as_strike"],
                name="reports_rep_reporte_01b8c1_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["content_type", "object_id"],
                name="reports_rep_content_7967a9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userreview",
            index=models.Index(
                fields=["user", "status"], name="reports_use_user_id_a90172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userreview",
            index=models.Index(
                fields=["status", "-created_at"], name="reports_use_status_941275_idx"
            ),
        ),
    ]
