export const PRODUCT_CATEGORIES = [
  { value: '', label: 'Select Category' },
  { value: 'desktop', label: 'Desktop Computer' },
  { value: 'laptop', label: 'Laptop/Notebook' },
  { value: 'tablet', label: 'Tablet' },
  { value: 'phone', label: 'Smartphone' },
  { value: 'tv', label: 'Television' },
  { value: 'monitor', label: 'Monitor' },
  { value: 'router', label: 'Router' },
  { value: 'modem', label: 'Modem' },
  { value: 'switch', label: 'Network Switch' },
  { value: 'access_point', label: 'Access Point' },
  { value: 'audio', label: 'Audio Equipment' },
  { value: 'speaker', label: 'Speaker/Soundbar' },
  { value: 'gaming', label: 'Gaming Console' },
  { value: 'handheld', label: 'Handheld Gaming' },
  { value: 'remote', label: 'Remote Control' },
  { value: 'power_supply', label: 'Power Supply' },
  { value: 'charger', label: 'Charger' },
  { value: 'iot', label: 'IoT Device' },
  { value: 'smart_home', label: 'Smart Home Hub' },
  { value: 'camera', label: 'Camera' },
  { value: 'printer', label: 'Printer' },
  { value: 'other', label: 'Other' },
];

export const REGIONS = [
  { value: 'global', label: 'Global/Universal' },
  { value: 'us', label: 'United States' },
  { value: 'eu', label: 'European Union' },
  { value: 'uk', label: 'United Kingdom' },
  { value: 'jp', label: 'Japan' },
  { value: 'cn', label: 'China' },
  { value: 'kr', label: 'South Korea' },
  { value: 'au', label: 'Australia' },
  { value: 'ca', label: 'Canada' },
  { value: 'other', label: 'Other' },
];

export const COMPONENT_TYPES = [
  { value: '', label: 'Select Type' },
  { value: 'ic', label: 'Integrated Circuit' },
  { value: 'mcu', label: 'Microcontroller' },
  { value: 'eeprom', label: 'EEPROM/Memory' },
  { value: 'transistor', label: 'Transistor' },
  { value: 'mosfet', label: 'MOSFET' },
  { value: 'diode', label: 'Diode' },
  { value: 'regulator', label: 'Voltage Regulator' },
  { value: 'opamp', label: 'Op-Amp' },
  { value: 'resistor', label: 'Resistor' },
  { value: 'capacitor', label: 'Capacitor' },
  { value: 'inductor', label: 'Inductor' },
  { value: 'transformer', label: 'Transformer' },
  { value: 'crystal', label: 'Crystal/Oscillator' },
  { value: 'relay', label: 'Relay' },
  { value: 'switch', label: 'Switch' },
  { value: 'connector', label: 'Connector' },
  { value: 'led', label: 'LED' },
  { value: 'display', label: 'Display/LCD' },
  { value: 'sensor', label: 'Sensor' },
  { value: 'module', label: 'Module' },
  { value: 'other', label: 'Other' },
];

export const RECIPE_CATEGORIES = [
  { value: 'audio', label: 'Audio' },
  { value: 'power_supply', label: 'Power Supply' },
  { value: 'iot', label: 'IoT' },
  { value: 'repair', label: 'Repair' },
  { value: 'lighting', label: 'Lighting' },
  { value: 'test_equipment', label: 'Test Equipment' },
  { value: 'radio', label: 'Radio' },
  { value: 'computing', label: 'Computing' },
  { value: 'robotics', label: 'Robotics' },
  { value: 'wearable', label: 'Wearable' },
  { value: 'other', label: 'Other' },
];

export const DIFFICULTIES = [
  { value: 'beginner', label: 'Beginner' },
  { value: 'intermediate', label: 'Intermediate' },
  { value: 'advanced', label: 'Advanced' },
  { value: 'expert', label: 'Expert' },
];
