# Generated by Django 5.1.15 on 2026-02-13 00:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("system_health", "System Health"),
                            ("system_performance", "System Performance"),
                            ("task_failure", "Task Failure"),
                            ("new_submission", "New Submission"),
                            ("new_report", "New Report"),
                            ("new_user_review", "New User Review"),
                            ("new_member", "New Member"),
                            ("new_subscriber", "New Subscriber"),
                            ("new_content", "New Content"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                (
                    "recipients",
                    models.JSONField(default=list, help_text="List of email addresses"),
                ),
                ("sent_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("sent", "Sent"), ("failed", "Failed")],
                        default="sent",
                        max_length=10,
                    ),
                ),
                ("error_message", models.TextField(blank=True, default="")),
            ],
            options={
                "verbose_name": "Notification Log",
                "verbose_name_plural": "Notification Logs",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Master switch — disables all notifications when off.",
                    ),
                ),
                (
                    "digest_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Batch community/content notifications into a daily digest.",
                    ),
                ),
                (
                    "system_health",
                    models.BooleanField(
                        default=True, help_text="Database, Redis, Celery outages"
                    ),
                ),
                (
                    "system_performance",
                    models.BooleanField(
                        default=True, help_text="CPU, memory, or disk usage exceeds 80%"
                    ),
                ),
                (
                    "task_failures",
                    models.BooleanField(default=True, help_text="Celery task errors"),
                ),
                (
                    "new_submission",
                    models.BooleanField(
                        default=True, help_text="Content submitted for review"
                    ),
                ),
                (
                    "new_report",
                    models.BooleanField(default=True, help_text="User reports filed"),
                ),
                (
                    "new_user_review",
                    models.BooleanField(
                        default=True, help_text="3-strike automatic user reviews"
                    ),
                ),
                (
                    "new_member",
                    models.BooleanField(
                        default=False, help_text="New user registrations"
                    ),
                ),
                (
                    "new_subscriber",
                    models.BooleanField(default=False, help_text="Newsletter signups"),
                ),
                (
                    "new_content",
                    models.BooleanField(
                        default=False, help_text="New products or components added"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Notification Preference",
                "verbose_name_plural": "Notification Preferences",
            },
        ),
    ]
