# Generated by Django 5.1.15 on 2026-01-29 13:16

import apps.products.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "manufacturer",
                    models.CharField(
                        db_index=True,
                        help_text="Product manufacturer (e.g., Samsung, Sony)",
                        max_length=200,
                    ),
                ),
                (
                    "model_number",
                    models.CharField(
                        db_index=True, help_text="Model number or name", max_length=200
                    ),
                ),
                (
                    "revision",
                    models.CharField(
                        blank=True,
                        help_text="Hardware revision if applicable",
                        max_length=50,
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        choices=[
                            ("us", "United States"),
                            ("eu", "European Union"),
                            ("uk", "United Kingdom"),
                            ("jp", "Japan"),
                            ("cn", "China"),
                            ("kr", "South Korea"),
                            ("tw", "Taiwan"),
                            ("au", "Australia"),
                            ("ca", "Canada"),
                            ("global", "Global/Universal"),
                            ("other", "Other"),
                        ],
                        default="global",
                        help_text="Region variant",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("desktop", "Desktop Computer"),
                            ("laptop", "Laptop/Notebook"),
                            ("tablet", "Tablet"),
                            ("server", "Server"),
                            ("sbc", "Single Board Computer"),
                            ("phone", "Smartphone"),
                            ("feature_phone", "Feature Phone"),
                            ("pager", "Pager/Beeper"),
                            ("tv", "Television"),
                            ("monitor", "Monitor"),
                            ("projector", "Projector"),
                            ("router", "Router"),
                            ("modem", "Modem"),
                            ("switch", "Network Switch"),
                            ("access_point", "Access Point"),
                            ("extender", "Range Extender"),
                            ("audio", "Audio Equipment"),
                            ("speaker", "Speaker/Soundbar"),
                            ("headphones", "Headphones/Earbuds"),
                            ("camera", "Camera"),
                            ("camcorder", "Camcorder"),
                            ("dvr", "DVR/NVR"),
                            ("streaming", "Streaming Device"),
                            ("gaming", "Gaming Console"),
                            ("handheld", "Handheld Gaming"),
                            ("controller", "Game Controller"),
                            ("keyboard", "Keyboard"),
                            ("mouse", "Mouse"),
                            ("printer", "Printer"),
                            ("scanner", "Scanner"),
                            ("webcam", "Webcam"),
                            ("remote", "Remote Control"),
                            ("universal_remote", "Universal Remote"),
                            ("power_supply", "Power Supply/Adapter"),
                            ("ups", "UPS/Battery Backup"),
                            ("charger", "Charger"),
                            ("power_strip", "Power Strip/Surge Protector"),
                            ("hdd", "Hard Drive"),
                            ("ssd", "SSD"),
                            ("nas", "NAS"),
                            ("usb_drive", "USB Drive"),
                            ("iot", "IoT Device"),
                            ("smart_home", "Smart Home Hub"),
                            ("thermostat", "Smart Thermostat"),
                            ("doorbell", "Smart Doorbell"),
                            ("security_cam", "Security Camera"),
                            ("appliance", "Home Appliance"),
                            ("hvac", "HVAC/Climate Control"),
                            ("kitchen", "Kitchen Appliance"),
                            ("automotive", "Automotive Electronics"),
                            ("dashcam", "Dash Camera"),
                            ("gps", "GPS/Navigation"),
                            ("obd", "OBD Device"),
                            ("medical", "Medical Device"),
                            ("industrial", "Industrial Equipment"),
                            ("test_equipment", "Test Equipment"),
                            ("radio", "Radio/Transceiver"),
                            ("drone", "Drone/UAV"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        help_text="Product category",
                        max_length=50,
                    ),
                ),
                (
                    "subcategory",
                    models.CharField(
                        blank=True, help_text="Optional subcategory", max_length=100
                    ),
                ),
                (
                    "year_manufactured",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Manufacturing year", null=True
                    ),
                ),
                (
                    "fcc_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="FCC ID for US devices",
                        max_length=50,
                    ),
                ),
                (
                    "ic_id",
                    models.CharField(
                        blank=True,
                        help_text="IC ID for Canadian devices",
                        max_length=50,
                    ),
                ),
                (
                    "part_number",
                    models.CharField(
                        blank=True, help_text="Manufacturer part number", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Product description and notes"
                    ),
                ),
                (
                    "teardown_notes",
                    models.TextField(
                        blank=True, help_text="Notes about the teardown process"
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether product has been approved by moderator",
                    ),
                ),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Featured on homepage"
                    ),
                ),
                (
                    "component_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of documented components"
                    ),
                ),
                (
                    "view_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times viewed"
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="High-resolution product image",
                        upload_to=apps.products.models.product_image_path,
                    ),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("overview", "Overview/Box"),
                            ("pcb_top", "PCB Top Side"),
                            ("pcb_bottom", "PCB Bottom Side"),
                            ("closeup", "Close-up Detail"),
                            ("label", "Label/Sticker"),
                            ("internal", "Internal View"),
                            ("schematic", "Schematic"),
                            ("other", "Other"),
                        ],
                        default="overview",
                        max_length=20,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Image caption or description",
                        max_length=500,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Order in image gallery"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("file_size", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "product image",
                "verbose_name_plural": "product images",
                "ordering": ["display_order", "uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Schematic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Schematic file (PDF, PNG, JPG, etc.)",
                        upload_to=apps.products.models.schematic_file_path,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="File extension/type", max_length=20
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "schematic_type",
                    models.CharField(
                        choices=[
                            ("full_schematic", "Full Schematic"),
                            ("block_diagram", "Block Diagram"),
                            ("pcb_layout", "PCB Layout"),
                            ("service_manual", "Service Manual"),
                            ("datasheet", "Component Datasheet"),
                            ("pinout", "Pinout Diagram"),
                            ("wiring_diagram", "Wiring Diagram"),
                            ("bom", "Bill of Materials"),
                            ("other", "Other Documentation"),
                        ],
                        default="full_schematic",
                        max_length=30,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title for this schematic", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about this schematic"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True,
                        help_text="Version or revision of the schematic",
                        max_length=50,
                    ),
                ),
                (
                    "page_count",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Number of pages (for PDFs)", null=True
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official", "Official/Manufacturer"),
                            ("community", "Community Contributed"),
                            ("reverse_engineered", "Reverse Engineered"),
                            ("fcc_filing", "FCC Filing"),
                            ("leaked", "Leaked Document"),
                            ("unknown", "Unknown Source"),
                        ],
                        default="community",
                        max_length=30,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL where this schematic was obtained"
                    ),
                ),
                (
                    "source_notes",
                    models.TextField(
                        blank=True, help_text="Attribution and source information"
                    ),
                ),
                (
                    "repair_relevance",
                    models.TextField(
                        blank=True, help_text="How this schematic helps with repairs"
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether schematic has been verified/approved",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
            ],
            options={
                "verbose_name": "schematic",
                "verbose_name_plural": "schematics",
                "ordering": ["schematic_type", "-uploaded_at"],
            },
        ),
    ]
