# Generated by Django 5.1.15 on 2026-01-29 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_products",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_images",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="schematic",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="schematics",
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="schematic",
            name="uploaded_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploaded_schematics",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["manufacturer", "model_number"],
                name="products_pr_manufac_948ea5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["category", "-created_at"],
                name="products_pr_categor_4d32d3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_approved", "-created_at"],
                name="products_pr_is_appr_7f2c91_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.UniqueConstraint(
                fields=("manufacturer", "model_number", "revision", "region"),
                name="unique_product_variant",
            ),
        ),
        migrations.AddIndex(
            model_name="schematic",
            index=models.Index(
                fields=["product", "schematic_type"],
                name="products_sc_product_f55a96_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="schematic",
            index=models.Index(
                fields=["is_approved", "-uploaded_at"],
                name="products_sc_is_appr_2fb573_idx",
            ),
        ),
    ]
