# Generated by Django 5.1.15 on 2026-02-12 19:01

import apps.products.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="High-resolution product image",
                upload_to=apps.products.models.product_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["png", "jpg", "jpeg", "gif", "webp"]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schematic",
            name="file",
            field=models.FileField(
                help_text="Schematic file (PDF, PNG, JPG, etc.)",
                upload_to=apps.products.models.schematic_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "gif",
                            "webp",
                            "svg",
                        ]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="ProductComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Comment text (max 2000 characters)", max_length=2000
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="product_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "product comment",
                "verbose_name_plural": "product comments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-created_at"],
                        name="products_pr_product_e649af_idx",
                    )
                ],
            },
        ),
    ]
