# Generated by Django 5.1.15 on 2026-02-15 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_trigram_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="is_approved",
            field=models.BooleanField(
                default=False, help_text="Whether image has been approved by moderator"
            ),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(
                fields=["is_approved", "-uploaded_at"],
                name="products_pr_is_appr_c1f155_idx",
            ),
        ),
    ]
