# Generated by Django 5.1.15 on 2026-02-15 23:43

from django.db import migrations


def approve_existing_images(apps, schema_editor):
    ProductImage = apps.get_model('products', 'ProductImage')
    ProductImage.objects.filter(is_approved=False).update(is_approved=True)


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_add_is_approved_to_productimage"),
    ]

    operations = [
        migrations.RunPython(approve_existing_images, migrations.RunPython.noop),
    ]
