# Generated by Django 5.1.15 on 2026-07-08 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_approve_existing_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schematic",
            name="schematic_type",
            field=models.CharField(
                choices=[
                    ("full_schematic", "Full Schematic"),
                    ("block_diagram", "Block Diagram"),
                    ("pcb_layout", "PCB Layout"),
                    ("service_manual", "Service Manual"),
                    ("user_manual", "User Manual"),
                    ("datasheet", "Component Datasheet"),
                    ("pinout", "Pinout Diagram"),
                    ("wiring_diagram", "Wiring Diagram"),
                    ("bom", "Bill of Materials"),
                    ("other", "Other Documentation"),
                ],
                default="full_schematic",
                max_length=30,
            ),
        ),
    ]
