# Generated by Django 5.1.15 on 2026-08-08 22:51

import apps.products.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0009_alter_product_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                help_text="High-resolution product image",
                upload_to=apps.products.models.product_image_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "png",
                            "jpg",
                            "jpeg",
                            "jfif",
                            "gif",
                            "webp",
                            "avif",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="schematic",
            name="file",
            field=models.FileField(
                help_text="Schematic file (PDF, PNG, JPG, etc.)",
                upload_to=apps.products.models.schematic_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "jfif",
                            "gif",
                            "webp",
                            "svg",
                        ]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Firmware",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Firmware binary (BIN, HEX, ROM, IMG, etc.)",
                        upload_to=apps.products.models.firmware_file_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "bin",
                                    "hex",
                                    "rom",
                                    "img",
                                    "dump",
                                    "fw",
                                    "elf",
                                    "zip",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        blank=True, help_text="File extension/type", max_length=20
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Descriptive title for this firmware", max_length=300
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Additional details about this firmware"
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        blank=True, help_text="Firmware version", max_length=50
                    ),
                ),
                (
                    "chip_architecture",
                    models.CharField(
                        blank=True,
                        help_text="Chip or architecture this firmware targets (e.g. ESP32, ARM Cortex-M4)",
                        max_length=100,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("official", "Official/Manufacturer Release"),
                            ("dumped", "Dumped from Device"),
                            ("community", "Community Contributed"),
                            ("reverse_engineered", "Reverse Engineered"),
                            ("leaked", "Leaked"),
                            ("unknown", "Unknown Source"),
                        ],
                        default="dumped",
                        max_length=30,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True, help_text="URL where this firmware was obtained"
                    ),
                ),
                (
                    "source_notes",
                    models.TextField(
                        blank=True,
                        help_text="Attribution, extraction method, and source information",
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False,
                        help_text="Whether firmware has been verified/approved",
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of times downloaded"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firmware_files",
                        to="products.product",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_firmware",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "firmware",
                "verbose_name_plural": "firmware",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-uploaded_at"],
                        name="products_fi_product_f72723_idx",
                    ),
                    models.Index(
                        fields=["is_approved", "-uploaded_at"],
                        name="products_fi_is_appr_842135_idx",
                    ),
                ],
            },
        ),
    ]
