# Generated by Django 5.1.15 on 2026-08-09 00:54

import apps.products.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0010_alter_component_component_type_and_more"),
        ("products", "0010_alter_productimage_image_alter_schematic_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ComponentSuggestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("pdf_manual", "PDF Manual/Service Doc"),
                            ("photo_ocr", "PCB Photo OCR"),
                        ],
                        default="pdf_manual",
                        max_length=20,
                    ),
                ),
                (
                    "source_file",
                    models.FileField(
                        blank=True,
                        help_text="The manual/document this was extracted from",
                        null=True,
                        upload_to=apps.products.models.suggestion_source_path,
                    ),
                ),
                ("page_number", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "extraction_context",
                    models.TextField(
                        blank=True,
                        help_text="Raw extracted row/line, for moderator sanity-checking",
                    ),
                ),
                (
                    "confidence",
                    models.CharField(
                        choices=[
                            ("high", "High (table extraction)"),
                            ("medium", "Medium"),
                            ("low", "Low (heuristic text match)"),
                        ],
                        default="medium",
                        max_length=10,
                    ),
                ),
                ("part_number", models.CharField(blank=True, max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=200)),
                ("reference_designator", models.CharField(blank=True, max_length=255)),
                ("component_type", models.CharField(blank=True, max_length=50)),
                ("package_type", models.CharField(blank=True, max_length=50)),
                ("description", models.CharField(blank=True, max_length=500)),
                ("value_raw", models.CharField(blank=True, max_length=100)),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                ("location_description", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "matched_component",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="components.component",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="component_suggestions",
                        to="products.product",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_component_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "component suggestion",
                "verbose_name_plural": "component suggestions",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["product", "-uploaded_at"],
                        name="products_co_product_5db8f4_idx",
                    ),
                    models.Index(
                        fields=["is_approved", "-uploaded_at"],
                        name="products_co_is_appr_3872f1_idx",
                    ),
                ],
            },
        ),
    ]
