# Generated by Django 5.1.15 on 2026-08-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0011_componentsuggestion"),
    ]

    operations = [
        migrations.AddField(
            model_name="schematic",
            name="bom_extracted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
