# Generated by Django 5.1.15 on 2026-08-09 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0012_schematic_bom_extracted_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="componentsuggestion",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("pdf_manual", "PDF Manual/Service Doc"),
                    ("schematic_ocr", "Schematic OCR"),
                    ("photo_ocr", "PCB Photo OCR"),
                ],
                default="pdf_manual",
                max_length=20,
            ),
        ),
    ]
