# Generated by Django 5.1.15 on 2026-08-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0013_alter_componentsuggestion_source_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productimage",
            name="image_type",
            field=models.CharField(
                choices=[
                    ("overview", "Overview/Box"),
                    ("pcb_top", "PCB Top Side"),
                    ("pcb_bottom", "PCB Bottom Side"),
                    ("closeup", "Close-up Detail"),
                    ("label", "Label/Sticker"),
                    ("internal", "Internal View"),
                    ("ports", "Ports/Connectors"),
                    ("damage", "Damage/Issue"),
                    ("schematic", "Schematic"),
                    ("other", "Other"),
                ],
                default="overview",
                max_length=20,
            ),
        ),
    ]
