# Generated by Django 5.1.15 on 2026-08-11 22:08

import apps.products.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_alter_productimage_image_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schematic",
            name="file",
            field=models.FileField(
                help_text="Schematic file (PDF, PNG, JPG, etc.)",
                upload_to=apps.products.models.schematic_file_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "png",
                            "jpg",
                            "jpeg",
                            "jfif",
                            "gif",
                            "webp",
                            "svg",
                            "zip",
                        ]
                    )
                ],
            ),
        ),
    ]
