# Generated by Django 5.1.15 on 2026-08-28 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0017_alter_schematic_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="background_removed",
            field=models.BooleanField(
                default=False,
                help_text="Whether this image has had its background auto-removed",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="has_transparency",
            field=models.BooleanField(
                default=False,
                help_text="Whether this image already has a transparent background",
            ),
        ),
    ]
