# Generated by Django 6.0.8 on 2026-08-31 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0020_remove_svg_schematic_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="source_url",
            field=models.URLField(
                blank=True,
                help_text="External source (e.g. wiki page) this documentation was derived from",
            ),
        ),
    ]
