# Generated by Django 5.1.15 on 2026-08-28 02:04

import apps.media_tools.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundRemovalPreview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        upload_to=apps.media_tools.models.bg_removal_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "png",
                                    "jpg",
                                    "jpeg",
                                    "jfif",
                                    "gif",
                                    "webp",
                                    "avif",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "result",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.media_tools.models.bg_removal_upload_path,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "model_name",
                    models.CharField(
                        choices=[
                            ("u2net", "General purpose (default)"),
                            (
                                "isnet-general-use",
                                "General purpose (sharper edges, newer model)",
                            ),
                            ("u2netp", "Fast/lightweight (lower quality)"),
                        ],
                        default="u2net",
                        max_length=30,
                    ),
                ),
                ("alpha_matting", models.BooleanField(default=False)),
                ("foreground_threshold", models.PositiveSmallIntegerField(default=240)),
                ("background_threshold", models.PositiveSmallIntegerField(default=10)),
                ("erode_size", models.PositiveSmallIntegerField(default=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bg_removal_previews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["created_at"], name="media_tools_created_352998_idx"
                    )
                ],
            },
        ),
    ]
