# Generated by Django 5.1.15 on 2026-08-28 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("components", "0011_componentimage_background_removed_and_more"),
        ("media_tools", "0001_initial"),
        ("products", "0018_productimage_background_removed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="backgroundremovalpreview",
            name="applied_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="backgroundremovalpreview",
            name="component_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bg_removal_previews",
                to="components.componentimage",
            ),
        ),
        migrations.AddField(
            model_name="backgroundremovalpreview",
            name="product_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bg_removal_previews",
                to="products.productimage",
            ),
        ),
    ]
