# Generated by Django 5.1.15 on 2026-08-28 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media_tools", "0002_backgroundremovalpreview_applied_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="backgroundremovalpreview",
            name="model_name",
            field=models.CharField(
                choices=[
                    (
                        "isnet-general-use",
                        "General purpose (sharper edges, newer model) (default)",
                    ),
                    ("u2net", "General purpose (older model)"),
                    ("u2netp", "Fast/lightweight (lower quality)"),
                ],
                default="isnet-general-use",
                max_length=30,
            ),
        ),
    ]
